"""3rd migration

Revision ID: 64eb79843a30
Revises: d71e7301b13b
Create Date: 2025-07-17 13:41:48.715889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64eb79843a30'
down_revision: Union[str, Sequence[str], None] = 'd71e7301b13b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact', sa.Integer(), nullable=True))
    op.drop_column('users', 'contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contacts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'contact')
    # ### end Alembic commands ###
